# Form implementation generated from reading ui file 'view.ui'
#
# Created by: PyQt6 UI code generator 6.6.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.document_listWidget = QtWidgets.QListWidget(parent=self.centralwidget)
        self.document_listWidget.setGeometry(QtCore.QRect(10, 90, 221, 461))
        self.document_listWidget.setObjectName("document_listWidget")
        self.search_lineEdit = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.search_lineEdit.setGeometry(QtCore.QRect(10, 30, 411, 31))
        self.search_lineEdit.setText("")
        self.search_lineEdit.setObjectName("search_lineEdit")
        self.document_textEdit = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.document_textEdit.setGeometry(QtCore.QRect(290, 90, 501, 501))
        self.document_textEdit.setReadOnly(True)
        self.document_textEdit.setObjectName("document_textEdit")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 10, 111, 16))
        self.label.setObjectName("label")
        self.search_pushButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.search_pushButton.setGeometry(QtCore.QRect(440, 30, 91, 31))
        self.search_pushButton.setObjectName("search_pushButton")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 70, 111, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(290, 70, 111, 16))
        self.label_3.setObjectName("label_3")
        self.add_document_pushButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.add_document_pushButton.setGeometry(QtCore.QRect(10, 560, 221, 31))
        self.add_document_pushButton.setObjectName("add_document_pushButton")
        self.label_4 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(646, 70, 141, 20))
        self.label_4.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.label_4.setStyleSheet("font-color:rgb(116, 160, 255);")
        self.label_4.setObjectName("label_4")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Document searcher"))
        self.document_textEdit.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8pt;\"><br /></p></body></html>"))
        self.label.setText(_translate("MainWindow", "Поисковой запрос"))
        self.search_pushButton.setText(_translate("MainWindow", "Поиск"))
        self.label_2.setText(_translate("MainWindow", "Список документов"))
        self.label_3.setText(_translate("MainWindow", "Документ"))
        self.add_document_pushButton.setText(_translate("MainWindow", "Добавить документ"))
        self.label_4.setText(_translate("MainWindow", "Ссылка на документ"))
